4/14

In [1]:
# Discription: Calculate game result of predicting COVID-19 confirmed cases from 5 countries til April 14, 2020(giving confirmed cases til April 7, 2020), use MAE/RMSE as indicator, 10 competitors joined. 
# Author: Lana Chen
# Date: April 14, 2020

In [2]:
import pandas as pd
import numpy as np
#from sklearn.metrics import mean_squared_error, mean_absolute_error
import math
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [3]:
df_covid = pd.read_excel('./src/covid_20200414.xlsx')
df_covid.columns

Index(['Unnamed: 0', 'Name', 'Taiwan', 'Italy', 'Germany', 'USA', 'UK'], dtype='object')

In [4]:
df_covid = df_covid[['Name', 'Taiwan', 'Italy', 'Germany', 'USA', 'UK']]
df_covid

        Name  Taiwan   Italy  Germany     USA     UK
0    player1     405  129440   101064  379030  43483
1    player2     421  123456    99999  333333  43210
2    player3     430  135476    88888  267890  43250
3    player4     499  132152    95124  312665  45666
4    player5     402  133339    97653  277777  44582
5    player6     420  133000    99000  300000  53000
6    player7     406  134000    93000  355000  49300
7    player8     420  140000   100000  310000  45000
8    player9     500  140000   100000  360000  46432
9   player10     415  142011    93200  352110  43211
10  player11     412  146000    92000  360000  50000
11  player12     429  139557    90934  282438  37632
12  player13     400  135000   100000  420000  41000

4/7實際感染人數:
Taiwan:376
Italy:132547
Germany:104515
USA:367776
UK:51608

4/14實際感染人數:
Taiwan:
Italy:
Germany:
USA:
UK:

In [5]:
true = [393,159516,131366,587337,88621]
last_week = [ 376,132547,104515,367776,51608 ]
this_week = true

In [6]:
#3/24
_0324=[215,63927,30344,46378,6650]

#3/31
_0331=[322,101739,68329,164408,22141]

#4/7
_0417=[376,132547,104515,367776,51608]

#4/14
_0414=[393,159516,131366,587337,88621]

In [7]:
#相對誤差MAE
#MAE
mae_loss=[]
for i in range(len(df_covid)):
    a_classmate = df_covid.loc[i]
    a_classmate_pred = [ a_classmate.Taiwan, a_classmate.Italy , a_classmate.Germany, a_classmate.USA, a_classmate.UK ]
    loss=0
    for j in range(5):
        loss+=( abs( true[j]-a_classmate_pred[j] )/true[j] )
    loss/=5
    mae_loss.append(loss)
mae_loss

[0.26274984746608265,
 0.2961933104740876,
 0.32481335045990406,
 0.33390216042975424,
 0.2935261642378499,
 0.2744956157434967,
 0.26487348968562696,
 0.2788458141284835,
 0.2993005422612625,
 0.2738307828255203,
 0.25112151503470226,
 0.32379758063744174,
 0.24650666554489406]

In [8]:
#相對誤差RMSE
#RMSE
rmse_loss=[]
for i in range(len(df_covid)):
    a_classmate = df_covid.loc[i]
    a_classmate_pred = [ a_classmate.Taiwan, a_classmate.Italy , a_classmate.Germany, a_classmate.USA, a_classmate.UK ]
    loss=0
    for j in range(5):
        loss+=( math.pow( (true[j]-a_classmate_pred[j])/true[j], 2)  )
    loss/=5
    loss=math.sqrt(loss)
    rmse_loss.append(loss)
rmse_loss

[0.3081884380984199,
 0.33549744005624343,
 0.3725753484768516,
 0.35550817206358726,
 0.35158211806033324,
 0.3143097381651527,
 0.3050659627217701,
 0.32922511062330206,
 0.3232828804763525,
 0.32327816527597125,
 0.2963297662570706,
 0.3792893630552694,
 0.30029043526605464]

In [9]:
#IAE(Increas Absolute Error)
#上週五國實際確診人數
#這週五國實際確診人數:
increase_true = abs( np.array(last_week) - np.array(this_week) )
iae_loss=[]
for i in range(len(df_covid)):
    a_classmate = df_covid.loc[i]
    a_classmate_pred = [ a_classmate.Taiwan, a_classmate.Italy , a_classmate.Germany, a_classmate.USA, a_classmate.UK ]
    loss=0
    for j in range(5):
        loss+=( abs( true[j]-a_classmate_pred[j] )/ increase_true[j] )
    loss/=5
    iae_loss.append(loss)
iae_loss

[1.0235746838001427,
 1.3072204675441363,
 1.4661203071414317,
 2.2022458113322734,
 1.071066534290412,
 1.209582249463006,
 1.0520445213075138,
 1.184341252561816,
 2.072234472015229,
 1.1325626999795237,
 1.0327532072053007,
 1.4259565712849849,
 0.9075408279065347]

In [10]:
#merge form
classmate_loss = df_covid
classmate_loss[u'MAE'] = mae_loss
classmate_loss[u'RMSE'] = rmse_loss
classmate_loss[u'IAE'] = iae_loss
classmate_loss

        Name  Taiwan   Italy  Germany     USA     UK       MAE      RMSE       IAE
0    player1     405  129440   101064  379030  43483  0.262750  0.308188  1.023575
1    player2     421  123456    99999  333333  43210  0.296193  0.335497  1.307220
2    player3     430  135476    88888  267890  43250  0.324813  0.372575  1.466120
3    player4     499  132152    95124  312665  45666  0.333902  0.355508  2.202246
4    player5     402  133339    97653  277777  44582  0.293526  0.351582  1.071067
5    player6     420  133000    99000  300000  53000  0.274496  0.314310  1.209582
6    player7     406  134000    93000  355000  49300  0.264873  0.305066  1.052045
7    player8     420  140000   100000  310000  45000  0.278846  0.329225  1.184341
8    player9     500  140000   100000  360000  46432  0.299301  0.323283  2.072234
9   player10     415  142011    93200  352110  43211  0.273831  0.323278  1.132563
10  player11     412  146000    92000  360000  50000  0.251122  0.296330  1.032753
11  player12     429  139557    90934  282438  37632  0.323798  0.379289  1.425957
12  player13     400  135000   100000  420000  41000  0.246507  0.300290  0.907541

In [11]:
#print the winner
print("相對MAE最小的人是：\t", classmate_loss.Name[classmate_loss.MAE.argmin()] )
print("相對RMSE最小的人是：\t", classmate_loss.Name[classmate_loss.RMSE.argmin()] )
print("相對IAE最小的人是：\t", classmate_loss.Name[classmate_loss.IAE.argmin()] )

相對MAE最小的人是：	 player13
相對RMSE最小的人是：	 player11
相對IAE最小的人是：	 player13

In [12]:
rank_tw,rank_italy,rank_germany,rank_usa,rank_uk=[],[],[],[],[]
for i in range(len(classmate_loss)):
    rank_tw.append( abs(classmate_loss.Taiwan[i]-true[0]) )
    rank_italy.append( abs(classmate_loss.Italy[i]-true[1]) )
    rank_germany.append( abs(classmate_loss.Germany[i]-true[2]) )
    rank_usa.append( abs(classmate_loss.USA[i]-true[3]) )
    rank_uk.append( abs(classmate_loss.UK[i]-true[4]) )
df_all = pd.DataFrame({'Name':classmate_loss.Name,'Taiwan':classmate_loss.Taiwan, 'Italy':classmate_loss.Italy,\
                       'Germany':classmate_loss.Germany, 'USA':classmate_loss.USA,'UK':classmate_loss.UK,\
                       'tw_rank':rank_tw,'italy_rank':rank_italy,\
                       'germany_rank':rank_germany,'usa_rank':rank_usa,'uk_rank':rank_uk})

df_all["Rank_Taiwan"] = df_all["tw_rank"].rank()
df_all["Rank_Italy"] = df_all["italy_rank"].rank()
df_all["Rank_Germany"] = df_all["germany_rank"].rank()
df_all["Rank_USA"] = df_all["usa_rank"].rank()
df_all["Rank_UK"] = df_all["uk_rank"].rank()
df_all['Rank_Sum']=df_all["Rank_Taiwan"]+df_all["Rank_Italy"]+df_all["Rank_Germany"]+df_all["Rank_USA"]+df_all["Rank_UK"]
df_all['MAE'] = classmate_loss.MAE
df_all['RMSE'] = classmate_loss.RMSE
df_all['IAE'] = classmate_loss.IAE
df_all['Rank_MAE'] = df_all['MAE'].rank()
df_all['Rank_RMSE'] = df_all['RMSE'].rank()
df_all['Rank_IAE'] = df_all['IAE'].rank()
df_all.drop(['tw_rank','italy_rank','germany_rank','usa_rank','uk_rank'],axis=1,inplace=True)
df_all

        Name  Taiwan   Italy  Germany     USA     UK  Rank_Taiwan  Rank_Italy  Rank_Germany  Rank_USA  Rank_UK  Rank_Sum       MAE      RMSE       IAE  Rank_MAE  Rank_RMSE  Rank_IAE
0    player1     405  129440   101064  379030  43483          3.0        12.0           1.0       2.0      8.0      26.0  0.262750  0.308188  1.023575       3.0        4.0       2.0
1    player2     421  123456    99999  333333  43210          9.0        13.0           5.0       7.0     11.0      45.0  0.296193  0.335497  1.307220       9.0        9.0       9.0
2    player3     430  135476    88888  267890  43250         11.0         6.0          13.0      13.0      9.0      52.0  0.324813  0.372575  1.466120      12.0       12.0      11.0
3    player4     499  132152    95124  312665  45666         12.0        11.0           8.0       8.0      5.0      44.0  0.333902  0.355508  2.202246      13.0       11.0      13.0
4    player5     402  133339    97653  277777  44582          2.0         9.0           7.0      12.0      7.0      37.0  0.293526  0.351582  1.071067       8.0       10.0       5.0
5    player6     420  133000    99000  300000  53000          7.5        10.0           6.0      10.0      1.0      34.5  0.274496  0.314310  1.209582       6.0        5.0       8.0
6    player7     406  134000    93000  355000  49300          4.0         8.0          10.0       5.0      3.0      30.0  0.264873  0.305066  1.052045       4.0        3.0       4.0
7    player8     420  140000   100000  310000  45000          7.5         3.5           3.0       9.0      6.0      29.0  0.278846  0.329225  1.184341       7.0        8.0       7.0
8    player9     500  140000   100000  360000  46432         13.0         3.5           3.0       3.5      4.0      27.0  0.299301  0.323283  2.072234      10.0        7.0      12.0
9   player10     415  142011    93200  352110  43211          6.0         2.0           9.0       6.0     10.0      33.0  0.273831  0.323278  1.132563       5.0        6.0       6.0
10  player11     412  146000    92000  360000  50000          5.0         1.0          11.0       3.5      2.0      22.5  0.251122  0.296330  1.032753       2.0        1.0       3.0
11  player12     429  139557    90934  282438  37632         10.0         5.0          12.0      11.0     13.0      51.0  0.323798  0.379289  1.425957      11.0       13.0      10.0
12  player13     400  135000   100000  420000  41000          1.0         7.0           3.0       1.0     12.0      24.0  0.246507  0.300290  0.907541       1.0        2.0       1.0

In [13]:
df_all.loc[len(df_all)] = ['真實感染人數', true[0], true[1], true[2], true[3], true[4],-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1]
df_all

        Name  Taiwan   Italy  Germany     USA     UK  Rank_Taiwan  Rank_Italy  Rank_Germany  Rank_USA  Rank_UK  Rank_Sum       MAE      RMSE       IAE  Rank_MAE  Rank_RMSE  Rank_IAE
0    player1     405  129440   101064  379030  43483          3.0        12.0           1.0       2.0      8.0      26.0  0.262750  0.308188  1.023575       3.0        4.0       2.0
1    player2     421  123456    99999  333333  43210          9.0        13.0           5.0       7.0     11.0      45.0  0.296193  0.335497  1.307220       9.0        9.0       9.0
2    player3     430  135476    88888  267890  43250         11.0         6.0          13.0      13.0      9.0      52.0  0.324813  0.372575  1.466120      12.0       12.0      11.0
3    player4     499  132152    95124  312665  45666         12.0        11.0           8.0       8.0      5.0      44.0  0.333902  0.355508  2.202246      13.0       11.0      13.0
4    player5     402  133339    97653  277777  44582          2.0         9.0           7.0      12.0      7.0      37.0  0.293526  0.351582  1.071067       8.0       10.0       5.0
5    player6     420  133000    99000  300000  53000          7.5        10.0           6.0      10.0      1.0      34.5  0.274496  0.314310  1.209582       6.0        5.0       8.0
6    player7     406  134000    93000  355000  49300          4.0         8.0          10.0       5.0      3.0      30.0  0.264873  0.305066  1.052045       4.0        3.0       4.0
7    player8     420  140000   100000  310000  45000          7.5         3.5           3.0       9.0      6.0      29.0  0.278846  0.329225  1.184341       7.0        8.0       7.0
8    player9     500  140000   100000  360000  46432         13.0         3.5           3.0       3.5      4.0      27.0  0.299301  0.323283  2.072234      10.0        7.0      12.0
9   player10     415  142011    93200  352110  43211          6.0         2.0           9.0       6.0     10.0      33.0  0.273831  0.323278  1.132563       5.0        6.0       6.0
10  player11     412  146000    92000  360000  50000          5.0         1.0          11.0       3.5      2.0      22.5  0.251122  0.296330  1.032753       2.0        1.0       3.0
11  player12     429  139557    90934  282438  37632         10.0         5.0          12.0      11.0     13.0      51.0  0.323798  0.379289  1.425957      11.0       13.0      10.0
12  player13     400  135000   100000  420000  41000          1.0         7.0           3.0       1.0     12.0      24.0  0.246507  0.300290  0.907541       1.0        2.0       1.0
13    真實感染人數     393  159516   131366  587337  88621         -1.0        -1.0          -1.0      -1.0     -1.0      -1.0 -1.000000 -1.000000 -1.000000      -1.0       -1.0      -1.0

In [14]:
df_all=df_all[['Name', 'Taiwan','Italy','Germany','USA','UK','Rank_Sum', 'Rank_Taiwan', 'Rank_Italy','Rank_Germany','Rank_USA','Rank_UK','MAE','RMSE','IAE','Rank_MAE','Rank_RMSE','Rank_IAE']]
df_all

        Name  Taiwan   Italy  Germany     USA     UK  Rank_Sum  Rank_Taiwan  Rank_Italy  Rank_Germany  Rank_USA  Rank_UK       MAE      RMSE       IAE  Rank_MAE  Rank_RMSE  Rank_IAE
0    player1     405  129440   101064  379030  43483      26.0          3.0        12.0           1.0       2.0      8.0  0.262750  0.308188  1.023575       3.0        4.0       2.0
1    player2     421  123456    99999  333333  43210      45.0          9.0        13.0           5.0       7.0     11.0  0.296193  0.335497  1.307220       9.0        9.0       9.0
2    player3     430  135476    88888  267890  43250      52.0         11.0         6.0          13.0      13.0      9.0  0.324813  0.372575  1.466120      12.0       12.0      11.0
3    player4     499  132152    95124  312665  45666      44.0         12.0        11.0           8.0       8.0      5.0  0.333902  0.355508  2.202246      13.0       11.0      13.0
4    player5     402  133339    97653  277777  44582      37.0          2.0         9.0           7.0      12.0      7.0  0.293526  0.351582  1.071067       8.0       10.0       5.0
5    player6     420  133000    99000  300000  53000      34.5          7.5        10.0           6.0      10.0      1.0  0.274496  0.314310  1.209582       6.0        5.0       8.0
6    player7     406  134000    93000  355000  49300      30.0          4.0         8.0          10.0       5.0      3.0  0.264873  0.305066  1.052045       4.0        3.0       4.0
7    player8     420  140000   100000  310000  45000      29.0          7.5         3.5           3.0       9.0      6.0  0.278846  0.329225  1.184341       7.0        8.0       7.0
8    player9     500  140000   100000  360000  46432      27.0         13.0         3.5           3.0       3.5      4.0  0.299301  0.323283  2.072234      10.0        7.0      12.0
9   player10     415  142011    93200  352110  43211      33.0          6.0         2.0           9.0       6.0     10.0  0.273831  0.323278  1.132563       5.0        6.0       6.0
10  player11     412  146000    92000  360000  50000      22.5          5.0         1.0          11.0       3.5      2.0  0.251122  0.296330  1.032753       2.0        1.0       3.0
11  player12     429  139557    90934  282438  37632      51.0         10.0         5.0          12.0      11.0     13.0  0.323798  0.379289  1.425957      11.0       13.0      10.0
12  player13     400  135000   100000  420000  41000      24.0          1.0         7.0           3.0       1.0     12.0  0.246507  0.300290  0.907541       1.0        2.0       1.0
13    真實感染人數     393  159516   131366  587337  88621      -1.0         -1.0        -1.0          -1.0      -1.0     -1.0 -1.000000 -1.000000 -1.000000      -1.0       -1.0      -1.0

In [15]:
df_all1=df_all[['Name', 'Taiwan','Italy','Germany','USA','UK','Rank_Sum', 'Rank_Taiwan', 'Rank_Italy','Rank_Germany','Rank_USA','Rank_UK']]
df_all1

        Name  Taiwan   Italy  Germany     USA     UK  Rank_Sum  Rank_Taiwan  Rank_Italy  Rank_Germany  Rank_USA  Rank_UK
0    player1     405  129440   101064  379030  43483      26.0          3.0        12.0           1.0       2.0      8.0
1    player2     421  123456    99999  333333  43210      45.0          9.0        13.0           5.0       7.0     11.0
2    player3     430  135476    88888  267890  43250      52.0         11.0         6.0          13.0      13.0      9.0
3    player4     499  132152    95124  312665  45666      44.0         12.0        11.0           8.0       8.0      5.0
4    player5     402  133339    97653  277777  44582      37.0          2.0         9.0           7.0      12.0      7.0
5    player6     420  133000    99000  300000  53000      34.5          7.5        10.0           6.0      10.0      1.0
6    player7     406  134000    93000  355000  49300      30.0          4.0         8.0          10.0       5.0      3.0
7    player8     420  140000   100000  310000  45000      29.0          7.5         3.5           3.0       9.0      6.0
8    player9     500  140000   100000  360000  46432      27.0         13.0         3.5           3.0       3.5      4.0
9   player10     415  142011    93200  352110  43211      33.0          6.0         2.0           9.0       6.0     10.0
10  player11     412  146000    92000  360000  50000      22.5          5.0         1.0          11.0       3.5      2.0
11  player12     429  139557    90934  282438  37632      51.0         10.0         5.0          12.0      11.0     13.0
12  player13     400  135000   100000  420000  41000      24.0          1.0         7.0           3.0       1.0     12.0
13    真實感染人數     393  159516   131366  587337  88621      -1.0         -1.0        -1.0          -1.0      -1.0     -1.0

In [16]:
df_all2=df_all[['Name', 'Taiwan','Italy','Germany','USA','UK','MAE','RMSE','IAE','Rank_MAE','Rank_RMSE','Rank_IAE']]
df_all2

        Name  Taiwan   Italy  Germany     USA     UK       MAE      RMSE       IAE  Rank_MAE  Rank_RMSE  Rank_IAE
0    player1     405  129440   101064  379030  43483  0.262750  0.308188  1.023575       3.0        4.0       2.0
1    player2     421  123456    99999  333333  43210  0.296193  0.335497  1.307220       9.0        9.0       9.0
2    player3     430  135476    88888  267890  43250  0.324813  0.372575  1.466120      12.0       12.0      11.0
3    player4     499  132152    95124  312665  45666  0.333902  0.355508  2.202246      13.0       11.0      13.0
4    player5     402  133339    97653  277777  44582  0.293526  0.351582  1.071067       8.0       10.0       5.0
5    player6     420  133000    99000  300000  53000  0.274496  0.314310  1.209582       6.0        5.0       8.0
6    player7     406  134000    93000  355000  49300  0.264873  0.305066  1.052045       4.0        3.0       4.0
7    player8     420  140000   100000  310000  45000  0.278846  0.329225  1.184341       7.0        8.0       7.0
8    player9     500  140000   100000  360000  46432  0.299301  0.323283  2.072234      10.0        7.0      12.0
9   player10     415  142011    93200  352110  43211  0.273831  0.323278  1.132563       5.0        6.0       6.0
10  player11     412  146000    92000  360000  50000  0.251122  0.296330  1.032753       2.0        1.0       3.0
11  player12     429  139557    90934  282438  37632  0.323798  0.379289  1.425957      11.0       13.0      10.0
12  player13     400  135000   100000  420000  41000  0.246507  0.300290  0.907541       1.0        2.0       1.0
13    真實感染人數     393  159516   131366  587337  88621 -1.000000 -1.000000 -1.000000      -1.0       -1.0      -1.0

In [17]:
df_all.to_excel('./dist/covid_game_20200414_0.xlsx')
df_all1.to_excel('./dist/covid_game_20200414_1.xlsx')
df_all2.to_excel('./dist/covid_game_20200414_2.xlsx')